version: "3.8"

services:
  web:
    image: fantinigiovanni/elysian-app:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "80:8000"
      - "443:8000"
    command: bash -c "poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
